replicaCount: 1

image:
  repository: ghcr.io/stariydedd/gitops-k8s-platform
  tag: "eadf3db"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
